name: PekoSrvFun
version: 1.4.0
authors: [MarioFinale, Hyperwave]
main: cl.mariofinale.PekoSrvFun
api-version: 1.19
website: https://github.com/MarioFinale/PekoSrvFun
depend: [LibsDisguises]
commands:
  peko:
    description: PekoSrvFun commands.
    usage: /Peko <blacklistworld - unblacklistworld - pekomon>